name: Build

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MAVEN_OPTS: -Xmx1024M

    steps:
      - uses: actions/checkout@v2

      - name: Clone Vitro
        run: git clone https://github.com/vivo-project/Vitro.git ../Vitro

      - name: Clone Vitro-languages
        run: git clone https://github.com/vivo-project/Vitro-languages.git ../Vitro-languages

      - name: Clone VIVO-languages
        run: git clone https://github.com/vivo-project/VIVO-languages.git ../VIVO-languages

      - name: Maven Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-cache-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-cache-m2-

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Maven Build
        run: |
          cd ../Vitro-languages
          mvn clean install
          cd ../VIVO-languages
          mvn clean install
          cd ../VIVO
          mvn clean package -s installer/example-settings.xml
